-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tiempo de generación: 25-05-2011 a las 11:33:12
-- Versión del servidor: 5.1.44
-- Versión de PHP: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `nscoder`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `eventos`
--

CREATE TABLE IF NOT EXISTS `eventos` (
  `latitude` float NOT NULL COMMENT 'latitude of event localization ',
  `longitude` float NOT NULL COMMENT 'longitude of event localization',
  `location` varchar(64) COLLATE utf8_spanish_ci NOT NULL,
  `name` varchar(64) COLLATE utf8_spanish_ci NOT NULL COMMENT 'envent''s name with twitt max length',
  `startdate` datetime NOT NULL COMMENT 'Envent celebration date',
  `shortdescription` varchar(144) COLLATE utf8_spanish_ci NOT NULL COMMENT 'detailed event description',
  `fulldescription` text COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`latitude`,`longitude`,`location`,`startdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='NSCoder events table';

--
-- Volcar la base de datos para la tabla `eventos`
--

INSERT INTO `eventos` (`latitude`, `longitude`, `location`, `name`, `startdate`, `shortdescription`, `fulldescription`) VALUES
(41.4069, 2.20992, 'CINC Barcelona', 'Hello NSCoder', '2011-05-28 11:00:10', 'Introducción iOS', 'El próximo sábado 28 de Mayo se da inicio a una serie de eventos organizados por NSCoder_BCN cuyo objetivo es el de mostrar cómo desarrollar aplicaciones para iOS.\r\nTambien tendremos la ocasion de conocer y probar un framework RAID muy potente llamado Omnis Studio.Con el,podemos crear potentes aplicaciones cliente-servidor,y clientes para nuestros dispositivos iOS,constituyendo Omnis Studio y Xcode un tándem ganador. Para ello,el director de producto y uno de los ingenieros de Omnis Italia se desplaza a Barcelona para darnos a conocer esta herramienta.\r\n\r\nEl nexo de unión de cada uno de los eventos va a consistir en la realización de una única aplicación con la que se pretende abarcar el máximo número de aspectos a tener en cuenta a la hora de iniciarse en el desarrollo de este tipo de aplicaciones.'),
(40.4673, -3.61622, 'Ifema', 'Intergift Madrid', '2011-09-14 11:00:10', 'Feria Internacional de Regalos', 'Intergift es una feria comercial y punto de encuentro para un sector con enorme potencial comercial. Selectivos y exigentes compradores pueden ver más recientes conceptos de diseño, calidad y creatividad, así como el creciente desarrollo de una cultura de la moda para el Hogar destacar. El contenido de Intergift se dividen en ocho sectores: los accesorios indispensables para la decoración y equipamiento integral del hogar, los más recientes propuestas en la industria textil, artículos para el hogar, artesanía, artículos de viaje y un completo repertorio de ideas originales para regalos informales y la fantasía y objetos útiles.'),
(40.4673, -3.61622, 'Ifema', 'SIMO NETWORK 2011', '2011-10-04 11:00:10', 'Feria Internacional de Servicios Y Soluciones TIC para empresas', 'SIMO NETWORK se presenta como una plataforma orientada a favorecer el encuentro y la relación profesional,  con un diseño de contenidos destinado a prescribir tecnología y mostrar a los responsables de negocio de la empresa  una perspectiva global de productos, servicios y soluciones tecnológicas que le permitirá identificar los recursos que harán más competitiva a su compañía'),
(40.4673, -3.61622, 'ifema', 'look internacional', '2011-10-14 13:25:48', 'La Feria de la Imagen y la Estetica Integral', 'PASARELA HAIR LOOK El mejor escenario en España para la presentación de las colecciones y shows de las fi rmas más relevantes del mundo de la peluquería, como la XI GALA INTERNACIONAL DE JÓVENES PROMESAS OMAT-HABIA. X-PRESION, VIDAL SASSOON y CLUB FIGARO.\r\n\r\nIII CONGRESO DE ESTÉTICA Este foro contó con ponencias y talleres sobre los aspectos más interesantes actualmente para la profesión, tales como cosmética, aparatología, estética y salud, terapias y tratamientos, marketing y gestión y los últimos avances en medicina estética. En todos los casos, fueron impartidos por los mejores profesionales y expertos en cada tema.\r\n\r\nII CONGRESO DE SPA  and  WELLNESS El espacio profesional monográfi co del Spa  and  Wellness, que incluyó diversas ponencias acerca de la integración del concepto spa como producto en hoteles, gimnasios y balnearios. Profesionales de reconocida experiencia analizaron los factores que garantizan el éxito y la rentabilidad de su integración.\r\n\r\nSEMINARIO DE GESTIÓN DE SPAS Esta iniciativa permitió a los alumnos adquirir conocimientos y técnicas sobre los instrumentos de gestión empresarial en las actividades de SPA and WELLNESS.\r\n\r\nCAMPEONATOS DE UÑAS Y MAQUILLAJE Una vez más, la convocatoria de estos campeonatos despertó gran interés entre los profesionales, registrando una elevada participación de concursantes y una gran asistencia de público a las distintas demostraciones.\r\n\r\nCURSOS DE FORMACIÓN DE PELUQUERÍA Numerosos profesionales asistieron a los diversos cursos de formación organizados en el salón, entre ellos, los impartidos por monitores internacionales de TONI and GUY; el taller Teach-In y clases magistrales de PIVOT POINT de la mano de Luis Romero y Design Forum. Paralelamente se celebró el taller Day off work (paso a paso) a cargo de PASSARO.'),
(41.4396, 2.14766, 'residencia universitaria Àgora', 'CampusMac 2011', '2011-06-28 13:27:05', ' talleres, ponencias y masterclass de todas las temáticas que envuelven al Mac', 'Como cada año, en la CampusMac se celebrarán talleres, ponencias y masterclass de todas las temáticas que envuelven al Mac. Este año, os presentamos los siguientes eventos*:\r\n\r\nTaller de GarageBand. Aprenderemos como funciona el programa de la suite iLife para crear música.\r\nPresentación de Photoshop CS5. Conoceremos las novedades del nuevo paquete de diseño de Adobe, de la mano de los responsables de Adobe España..\r\nTaller de Snow Leopard para Switchers. ¿Eres nuevo en Mac OS X? Todo lo que necesitas para que te olvides definitivamente de Windows y aprendas todo lo básico para dominar el sistema operativo de Apple.\r\niWork. Daremos un repaso a la suite iWork de Apple.\r\nMasterClass de Bento3. Los responsables de Filemaker España te enseñarán a sacarle partido a Bento 3 para tu Mac, iPhone o iPad.\r\nCreatividad y Producción: Cómo conseguir que la imaginación no tenga límites. Kotoc Estudios impartirá una Masterclass para desatar nuestra creatividad.\r\nWorkShop Painter 11. Como crear un dibujo desde 0 con el poderoso Painter 11 y las nuevas Cintiq 21 de Wacom.\r\nFinal Cut Pro. Iniciación a la edición de vídeo profesional con el software Final Cut Pro de Apple.\r\nConferencia Niko. El creador del popular Cálico Electrónico, charlará con nosotros y nos explicará sus nuevos planes de futuro.\r\nComposición y arte digital con Photoshop. Uso de las plumillas y el retoque fotográfico con PhotoShop.\r\nMac OSX Server. ¿Qué es? ¿Cómo funciona? ¿Qué se puede hacer? Conoceremos todos los secretos de Mac OSX Server\r\nGoogle Sketchup. Mostraremos como funciona el versátil programa de Google para realizar diseños en 3D.\r\nDiseño de Tipografías. Como usar OverType para crear tipografías únicas para nuestros trabajos de diseño.\r\nCalibración de Color sistemas Quato. Qué es y como calibrar el color de tu pantalla con los sistemas Quato.\r\nWeb 2.0 y SEO. Como optimizar nuestras páginas webs y blogs para conseguir un mejor resultado en los buscadores.\r\nProductividad con GTD y Mac. Como usar las herramientas de Google y nuestro Mac para ser más productivo.\r\nCharla de la Asociación Podcast. ¿Qué es la Asociación? ¿A qué se dedica?\r\nTaller de Switchers para niños. Los niños también podrán aprender como funciona Mac OS X.\r\n“Viaje por la história de Apple”. Charla sobre la história de Apple de la mano de Pedro Aznar.\r\niOS 4. Conoceremos los secretos del nuevo iPhone4 y iPad y su nuevo y flamante sistema operativo.\r\nGravina 82 en estado puro. Los Podcasters Sevillanos de Gravina 82 grabarán un programa en directo y nos dejarán… acortichados.'),
(51.529, -0.202904, 'Wembley Park (Londres).', 'BARÇA-MANCHESTER UNITED', '2011-05-28 21:00:00', 'Final Champions 2011', 'La historia se repite. Guardiola y Ferguson se volverán a ver las caras en una final de la Champions dos años después en un territorio de grato recuerdo culé: Wembley, escenario de la consecución de la primera Copa de Europa barcelonista.\r\n\r\nEl partido será retransmitido por televisión por TVE y TV3 y podrá así mismo seguirse también en el Miniestadi (con invitación) y en diversos cines de Barcelona que mostrarán el partido en 3D, cuyas entradas se pueden adquirir ya en Servicaixa.\r\n\r\nEl Barça cuenta con su plantilla al completo, recuperado Puyol, y con la moral altísima tras la consecución de la Liga y el pase a la final después de derrotar a su máximo rival. En una situación similar llega el ManU, campeón indiscutible de la mejor liga del mundo, que podrá contar con los Rooney, Chicharito, Giggs o Fletcher, que se perdió la anterior final de igual manera que lo hicieran Abidal o Dani Alves.\r\n\r\nLa UEFA designará al árbitro del partido como es habitual, durante las 48 horas previas al partido. Posibles onces iniciales:'),
(41.4234, 2.17057, 'Parc del Fòrum', 'Primavera Sound', '2011-05-25 13:29:23', 'San Miguel Primavera Sound 2011', 'San Miguel Primavera Sound 2011 se celebrará del 25 al 29 de mayo repartiéndose la programación entre los dos recintos históricos del festival: el 25 y el 29 de mayo las actuaciones se llevarán a cabo en el Poble Espanyol, el resto de días sucederán como viene siendo habitual en el Parc del Fòrum.\r\n\r\nPor si fuera poco la incorporación de Pulp como cabeza de cartel después de 10 años sin pisar juntos un escenario, los organizadores del festival barcelonés nos han sorprendido con una nueva tanda de confirmaciones entre las que destacan nombres como Animal Collective, Belle  and  Sebastiano The National, entre otros.\r\n\r\nPero hay más, pues también actuarán bandas tan importantes como The Flaming Lips, Fleet Foxes, Mogwai o Mercury Rev, que interpretarán al completo su obra Deserter´s Songs.'),
(37.8054, -0.834274, 'Auditorio Municipal Parque Almansa', 'XIV Festival Internacional de Jazz de San Javier', '2011-06-25 13:30:15', 'Cita con el mejor jazz y blues del panorama actual', 'Desde el 25 de junio y hasta el 30 de julio la ciudad murciana de San Javier se convertirá en punto de reunión de los amantes del jazz gracias al XIV Festival Internacional de Jazz de San Javier. Convertido en una de las citas ineludibles del género por méritos própios, el certamen siempre cuenta con grandes nombres del jazz en su cartel. Este año serán Wynton Marsalis con la Lincoln Center Orchestra, Erin Burdon  and  The Animals, John Pizzarelli con la Clayton Hamilton Jazz Orchestra, Chicago, Ramsey Lewis o Biel Ballester, entre otros. No puedes perderte la cita con el mejor jazz y blues del panorama actual.'),
(38.0268, -0.743937, 'San Agustín, 12.Almagro', 'Festival Internacional de Teatro Clásico de Almagro', '2011-07-01 13:31:15', 'El festival de teatro clásico más prestigioso de nuestro país.', 'Hablamos del Festival Internacional de Teatro Clásico de Almagro, que este año a su 33 edición, y con su nueva directora, la actriz, directora y autora dramática Natalia Menéndez , quien ha afirmado sentir como "un regalo" su designación. El Festival de Fotografía Photo España, dedicado este año a la reflexión sobre el tiempo, es el gran protagonista de nuestra sección de agenda. Los tres componentes principales de la banda barcelonesa San Leon, tocan en directo tres temas de su primer disco Bits  and  Pieces . Una música fresca que mezcla diversos estilos, el Pop, el rock, la rumba, el folk, y los ritmos tropicales.'),
(41.3837, 2.16702, 'CCCB/MACBA', 'Sónar 2011', '2011-06-16 13:32:00', 'Festival Internacional de Música Avanzada y Arte Multimedia', 'Sónar es un festival pionero y único en su formato y contenidos: un referente internacional de primer orden gracias a una cuidada oferta cultural que combina lo lúdico con lo artístico, la vanguardia y la experimentación con los artistas y tendencias más consolidados de las músicas electrónicas y sus interacciones e hibridaciones con otros géneros.\r\n\r\nLa propuesta artística de Sónar Barcelona se divide entre las actividades de Sónar de Día (conciertos, showcases, zona para profesionales, área expositiva), cuya principal esencia es el rastreo de nuevos talentos, y los grandes shows de Sónar de Noche, donde se presentan los nombres clave del panorama musical internacional.\r\n\r\nEl festival, además, propone cada año una serie de eventos paralelos en equipamientos culturales de Barcelona como L’Auditori o el CosmoCaixa y colaboraciones puntuales con otros eventos señalados del calendario de la ciudad (como el festival de verano GREC en la edición de 2010).\r\n\r\nMás de 84 mil personas disfrutaron en la pasada edición de 2010 de una cuidada programación que combina los grandes nombres de la electrónica actual con un amplio cartel de artistas y dj''s emergentes, líderes de las tendencias musicales y de la creación new media de nuestro tiempo.\r\n\r\nSónar se caracteriza además por ser un punto de encuentro para un público ávido de novedad y, de forma específica, para profesionales de todo el mundo de diversos sectores de las industrias creativas, que encuentran en el marco de SonarPro, el lugar ideal para hacer sus negocios y establecer contactos.\r\n\r\nAdemás de la sede de Barcelona, Sónar celebró en 2010, y por primera vez, otro festival simultáneo en A Coruña, con el nombre de Sónar Galicia. Sónar Galicia nació con un formato específico, y con una oferta musical y artística inspirada en el referente barcelonés. El nuevo festival ha gozado de gran éxito artístico y de público, con la asistencia de más de 14 mil personas en su primera edición. Sónar Galicia 2011 se celebrará los días 17 y 18 de junio.\r\n\r\nEl festival ha traspasado regularmente las fronteras españolas desde 2002 con eventos en distintos lugares del mundo, adaptando la filosofía Sónar a espacios y entornos singulares, y dando a conocer lo más interesante del talento nacional y de la escena de la ciudad donde se celebra. Hasta hoy, Sónar ha viajado a Londres (cita anual desde 2002), Nueva York, Buenos Aires, Sao Paulo, Seúl, Frankfurt, Chicago o Tokio, entre muchos otros destinos.');
